### ISSUE TITLE
options不能传递

### ISSUE THREAD

**Issue by ytd7777** [yuansir/toastr-for-laravel5#2]
$options = array_merge($config, $notification['options']);

$config 为[] 时，$notification['options']不管传什么 ，$options都为空

**Comment by yuansir** [comment]
@ytd7777 
src/Toastr.php  47行
```
if($config) {
                $options = array_merge($config, $notification['options']);
}
```
你说的是这个吗？$config 为 [] 时 不会执行 array_merge

**Comment by ytd7777** [comment]
en
